# Strip out the verilog paramters generated by xschem
# Also correct for any spice busses by replacing ".." with ":"

import re
import sys
import os

if __name__ == '__main__':
    in_file = sys.argv[1]
    out_file = sys.argv[2]

    verilog_param_start_rex = re.compile('^\#\(*', re.IGNORECASE)
    verilog_param_end_rex = re.compile('^\)$', re.IGNORECASE)
    x_rex = re.compile('^[ \t]*X[0-9]*[ (\t]*$', re.IGNORECASE)
    module_rex = re.compile('^module', re.IGNORECASE)

    with open(in_file, 'r') as ifile:
        bad_verilog  = ifile.readlines()

    skip = 0
    prev_line = ""

    modules = []

    for line in bad_verilog:
        module_match = module_rex.match(line)
        if module_match:
            modules.append(line.replace("module","").strip())



    with open(out_file, 'w') as ofile:
        for cur_line in bad_verilog:

            param_start_match = verilog_param_start_rex.match(cur_line)
            param_end_match = verilog_param_end_rex.match(cur_line)
            x_match = x_rex.match(cur_line)

            if x_match:
                if prev_line.strip() not in modules:
                    declaration = "sky130_fd_sc_hd__" + prev_line.strip() + " " + cur_line.strip()
                    print(declaration, file=ofile)
                    skip = 1
                    prev_line = cur_line
                    continue

            if skip:
                skip = 0
                prev_line = cur_line
                continue

            print(prev_line.replace("..", ":").strip(), file=ofile)
            prev_line = cur_line


        print(cur_line, file=ofile)

